name: turismapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.0.1
  http: ^1.2.1
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Background_login.jpg
    - assets/LOGO_MOCHI_GO.png