// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMSBYOuHvaqHGXmmrfaoRl9IArI54clGo',
    appId: '1:859710664558:web:a1f357bc464cda21539b7f',
    messagingSenderId: '859710664558',
    projectId: 'tourismapp-68738',
    authDomain: 'tourismapp-68738.firebaseapp.com',
    storageBucket: 'tourismapp-68738.appspot.com',
    measurementId: 'G-DMLGZ7WGPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oRJ43S-pQAPHG1bnkea7TsUvo1hNrfM',
    appId: '1:859710664558:android:807e1d708287e896539b7f',
    messagingSenderId: '859710664558',
    projectId: 'tourismapp-68738',
    storageBucket: 'tourismapp-68738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnpSwP0KGzQ7KAm3-Mizp25z2dqZ4flCM',
    appId: '1:859710664558:ios:f71c59af2eb28d05539b7f',
    messagingSenderId: '859710664558',
    projectId: 'tourismapp-68738',
    storageBucket: 'tourismapp-68738.appspot.com',
    iosBundleId: 'com.example.tourismapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnpSwP0KGzQ7KAm3-Mizp25z2dqZ4flCM',
    appId: '1:859710664558:ios:f71c59af2eb28d05539b7f',
    messagingSenderId: '859710664558',
    projectId: 'tourismapp-68738',
    storageBucket: 'tourismapp-68738.appspot.com',
    iosBundleId: 'com.example.tourismapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMSBYOuHvaqHGXmmrfaoRl9IArI54clGo',
    appId: '1:859710664558:web:cc52b73424a91079539b7f',
    messagingSenderId: '859710664558',
    projectId: 'tourismapp-68738',
    authDomain: 'tourismapp-68738.firebaseapp.com',
    storageBucket: 'tourismapp-68738.appspot.com',
    measurementId: 'G-7ZZCZQSFPQ',
  );
}
